apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-demo.fullname" . }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    {{- include "springboot-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "springboot-demo.name" . }}
    app.kubernetes.io/instances: {{ .Release.Name }}
